[technote]
id = "DMTN-330"
series_id = "DMTN"
canonical_url = "https://dmtn-330.lsst.io"
github_url = "https://github.com/lsst-dm/dmtn-330"
github_default_branch = "main"
date_created = 2025-10-22T20:41:30Z
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "David H."
name.family = "Irving"
internal_id = "irvingd"
orcid = "https://orcid.org/0009-0005-9099-4970"
[[technote.authors.affiliations]]
name = "NSF NOIRLab"
internal_id = "RubinOps"
address = "Tucson"
